# This is a minimal workflow.

name: Play with environment variables

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:

    runs-on: ubuntu-latest

    env:
      myVar: Some arbitrary value

    steps:
      - name: Hello
        run: echo "Hello there."


      - name: Do stuff
        run: |
          echo "Can I access the value?  '$myVar'"

      - name: Goodbye
        run: echo "Bye now!"

